#!/usr/bin/env bash
# Redirect
apt update -y
apt install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Replace the location block for /redirect_me with a redirect
sed -i '/location \/ {/a \\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default

service nginx start
