#!/usr/bin/env bash
# Redirect
apt update -y
apt install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/ a return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default
service nginx start
