#!/usr/bin/env bash

# Update packages and install Nginx
apt update -y
apt install -y nginx

# Create a default index page
echo "Hello World" > /var/www/html/index.nginx-debian.html

# Add rewrite rule for /redirect_me path
sed -i '/server_name _;/ a \
        location /redirect_me {\
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
        }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
